<script lang="ts">
import {deleteAccount,listAccounts,validateAccount} from "../lib/api";
import type {Account} from "../lib/api";
let rows=$state<Account[]>([]),query=$state(""),provider=$state("all"),status=$state("all"),busy=$state(""),error=$state("");
const providers=$derived([...new Set(rows.map(r=>r.provider))].sort());
const filtered=$derived(rows.filter(r=>{const q=query.toLowerCase();return(!q||[r.label,r.email??"",r.provider].some(v=>v.toLowerCase().includes(q)))&&(provider==="all"||r.provider===provider)&&(status==="all"||r.sessionStatus===status)}));
$effect(()=>{void load()});
async function load(){try{rows=await listAccounts();error=""}catch(e){error=e instanceof Error?e.message:String(e)}}
async function check(id:string){busy=id;try{await validateAccount(id);await load()}finally{busy=""}}
async function remove(r:Account){if(!confirm(`Account „${r.label}“ löschen?`))return;busy=r.id;try{await deleteAccount(r.id);await load()}finally{busy=""}}
const date=(v?:string)=>v?new Intl.DateTimeFormat("de-DE",{dateStyle:"short",timeStyle:"short"}).format(new Date(v)):"–";
</script>
<div class="page"><header><div><small>ACCOUNT REGISTER</small><h2>Accounts</h2><p>{filtered.length} von {rows.length} Konten</p></div><button onclick={load}>Aktualisieren</button></header><section class="filters"><input bind:value={query} placeholder="Suchen …"/><select bind:value={provider}><option value="all">Alle Provider</option>{#each providers as p}<option value={p}>{p}</option>{/each}</select><select bind:value={status}><option value="all">Alle Status</option><option value="valid">Gültig</option><option value="expired">Abgelaufen</option><option value="login-required">Login nötig</option><option value="error">Fehler</option></select></section>{#if error}<p class="error">{error}</p>{/if}<div class="grid"><table><thead><tr><th>#</th><th>Provider</th><th>Account</th><th>E-Mail</th><th>Plan</th><th>Status</th><th>Prio</th><th>Validiert</th><th>Zuletzt genutzt</th><th>Aktionen</th></tr></thead><tbody>{#each filtered as r,i (r.id)}<tr><td>{i+1}</td><td>{r.provider}</td><td><b>{r.label}</b><small>{r.id}</small></td><td>{r.email??"–"}</td><td>{r.plan??"unknown"}</td><td><span class="status {r.sessionStatus}">{r.sessionStatus}</span></td><td>{r.priority}</td><td>{date(r.lastValidatedAt)}</td><td>{date(r.lastUsedAt)}</td><td><button onclick={()=>check(r.id)} disabled={busy===r.id}>Prüfen</button><button class="danger" onclick={()=>remove(r)} disabled={busy===r.id}>Löschen</button></td></tr>{/each}</tbody></table></div></div>
<style>.page{padding:.25rem 0 2rem}header{display:flex;justify-content:space-between;align-items:end;margin-bottom:.6rem}header small{color:var(--accent-secondary)}h2{margin:.2rem 0}header p{margin:0;color:var(--muted)}button,input,select{min-height:34px;border:1px solid var(--border);border-radius:5px;background:var(--surface);color:var(--text);padding:0 .55rem}.filters{display:grid;grid-template-columns:1fr 190px 170px;gap:.4rem;padding:.5rem;border:1px solid var(--border);border-bottom:0;background:var(--card-bg)}.grid{overflow:auto;border:1px solid var(--border)}table{width:100%;min-width:1100px;border-collapse:collapse;font-size:.73rem}th,td{padding:.5rem .6rem;border-right:1px solid rgba(151,166,196,.12);border-bottom:1px solid rgba(151,166,196,.12);text-align:left;white-space:nowrap}th{position:sticky;top:0;background:#111b2d;color:#b8c4d8}tbody tr:hover{background:rgba(143,122,255,.06)}td small{display:block;color:var(--muted)}.status{padding:.15rem .4rem;border-radius:999px;background:rgba(145,160,184,.12)}.status.valid{color:var(--success)}.status.error,.status.expired,.status.login-required{color:var(--danger)}td button{margin-right:.25rem}.danger,.error{color:var(--danger)}@media(max-width:700px){.filters{grid-template-columns:1fr}}</style>