<script lang="ts">
import {onMount} from "svelte";
import {connectLiveLogs} from "../lib/live-logs";
import type {LiveLogEvent,LiveLogLevel} from "../lib/live-logs";
const order:Record<LiveLogLevel,number>={trace:10,debug:20,info:30,warn:40,error:50,fatal:60};
let logs=$state<LiveLogEvent[]>([]),pending=$state<LiveLogEvent[]>([]),paused=$state(false),query=$state(""),level=$state<LiveLogLevel>("trace"),state=$state("connecting");
const rows=$derived(logs.filter(r=>order[r.level]>=order[level]&&(!query||[r.level,r.name??"",r.message,r.context?JSON.stringify(r.context):""].some(v=>v.toLowerCase().includes(query.toLowerCase())))));
onMount(()=>connectLiveLogs(entry=>{if(paused)pending=[...pending.slice(-499),entry];else logs=[...logs.slice(-499),entry]},next=>state=next,150));
function toggle(){paused=!paused;if(!paused&&pending.length){logs=[...logs,...pending].slice(-500);pending=[]}}
const time=(v:string)=>new Intl.DateTimeFormat("de-DE",{hour:"2-digit",minute:"2-digit",second:"2-digit",fractionalSecondDigits:3}).format(new Date(v));
</script>
<div class="page"><header><div><small>EVENT REGISTER</small><h2>Live-Logs</h2><p>{rows.length} sichtbar · Verbindung {state}</p></div><div><button onclick={toggle}>{paused?`Fortsetzen (${pending.length})`:"Pausieren"}</button><button onclick={()=>{logs=[];pending=[]}}>Leeren</button></div></header><section class="filters"><input bind:value={query} placeholder="Logs durchsuchen …"/><select bind:value={level}><option value="trace">Trace+</option><option value="debug">Debug+</option><option value="info">Info+</option><option value="warn">Warn+</option><option value="error">Error+</option><option value="fatal">Fatal</option></select></section><div class="grid"><table><thead><tr><th>#</th><th>Zeit</th><th>Level</th><th>Quelle</th><th>Nachricht</th><th>Kontext</th></tr></thead><tbody>{#each rows as r,i (r.id)}<tr class="level-{r.level}"><td>{i+1}</td><td>{time(r.time)}</td><td><b>{r.level}</b></td><td>{r.name??"nova"}</td><td>{r.message||"(ohne Nachricht)"}</td><td><code>{r.context?JSON.stringify(r.context):"–"}</code></td></tr>{/each}</tbody></table></div></div>
<style>.page{padding:.25rem 0 2rem}header{display:flex;justify-content:space-between;align-items:end;margin-bottom:.6rem}header small{color:var(--accent-secondary)}h2{margin:.2rem 0}header p{margin:0;color:var(--muted)}header>div:last-child{display:flex;gap:.4rem}button,input,select{min-height:34px;border:1px solid var(--border);border-radius:5px;background:var(--surface);color:var(--text);padding:0 .55rem}.filters{display:grid;grid-template-columns:1fr 150px;gap:.4rem;padding:.5rem;border:1px solid var(--border);border-bottom:0;background:var(--card-bg)}.grid{height:70vh;overflow:auto;border:1px solid var(--border);background:#070d17}table{width:100%;min-width:1100px;border-collapse:collapse;font: .7rem "SFMono-Regular",Consolas,monospace}th,td{padding:.45rem .55rem;border-right:1px solid rgba(151,166,196,.1);border-bottom:1px solid rgba(151,166,196,.08);text-align:left;vertical-align:top}th{position:sticky;top:0;background:#111b2d;color:#b8c4d8}tbody tr:hover{background:rgba(143,122,255,.05)}td:nth-child(-n+4){white-space:nowrap}.level-warn td:nth-child(3){color:#ffd166}.level-error td:nth-child(3),.level-fatal td:nth-child(3){color:var(--danger)}.level-info td:nth-child(3){color:#86b7ff}code{white-space:pre-wrap;word-break:break-word;color:#93a4bc}@media(max-width:700px){.filters{grid-template-columns:1fr}}</style>