<script lang="ts">
import {getModels,refreshModels} from "../lib/api";
import type {Model} from "../lib/api";
let rows=$state<Model[]>([]),query=$state(""),provider=$state("all"),busy=$state(false),error=$state(""),copied=$state("");
const providers=$derived([...new Set(rows.map(r=>r.provider))].sort());
const filtered=$derived(rows.filter(r=>{const q=query.toLowerCase();return(!q||[r.name,r.id,r.provider].some(v=>v.toLowerCase().includes(q)))&&(provider==="all"||r.provider===provider)}));
$effect(()=>{void load()});
async function load(){try{rows=await getModels();error=""}catch(e){error=e instanceof Error?e.message:String(e)}}
async function refresh(){busy=true;try{rows=(await refreshModels()).models;error=""}catch(e){error=e instanceof Error?e.message:String(e)}finally{busy=false}}
async function copy(id:string){await navigator.clipboard.writeText(id);copied=id;setTimeout(()=>copied="",1200)}
</script>
<div class="page"><header><div><small>MODEL REGISTER</small><h2>Modelle</h2><p>{filtered.length} von {rows.length} Modellen</p></div><button onclick={refresh} disabled={busy}>{busy?"Aktualisiere …":"Cache aktualisieren"}</button></header><section class="filters"><input bind:value={query} placeholder="Modell oder ID suchen …"/><select bind:value={provider}><option value="all">Alle Provider</option>{#each providers as p}<option value={p}>{p}</option>{/each}</select></section>{#if error}<p class="error">{error}</p>{/if}<div class="grid"><table><thead><tr><th>#</th><th>Provider</th><th>Modell</th><th>Modell-ID</th><th>Text</th><th>Vision</th><th>Voice</th><th>Plugins</th><th>Status</th><th>Aktion</th></tr></thead><tbody>{#each filtered as r,i (r.id)}<tr><td>{i+1}</td><td>{r.provider}</td><td><b>{r.name}</b></td><td><code>{r.id}</code></td><td>{r.capabilities.text?"Ja":"–"}</td><td>{r.capabilities.vision?"Ja":"–"}</td><td>{r.capabilities.voice?"Ja":"–"}</td><td>{r.capabilities.plugins?"Ja":"–"}</td><td><span class:active={r.enabled}>{r.enabled?"Aktiv":"Inaktiv"}</span></td><td><button onclick={()=>copy(r.id)}>{copied===r.id?"Kopiert":"ID kopieren"}</button></td></tr>{/each}</tbody></table></div></div>
<style>.page{padding:.25rem 0 2rem}header{display:flex;justify-content:space-between;align-items:end;margin-bottom:.6rem}header small{color:var(--accent-secondary)}h2{margin:.2rem 0}header p{margin:0;color:var(--muted)}button,input,select{min-height:34px;border:1px solid var(--border);border-radius:5px;background:var(--surface);color:var(--text);padding:0 .55rem}.filters{display:grid;grid-template-columns:1fr 200px;gap:.4rem;padding:.5rem;border:1px solid var(--border);border-bottom:0;background:var(--card-bg)}.grid{overflow:auto;border:1px solid var(--border)}table{width:100%;min-width:1000px;border-collapse:collapse;font-size:.73rem}th,td{padding:.5rem .6rem;border-right:1px solid rgba(151,166,196,.12);border-bottom:1px solid rgba(151,166,196,.12);text-align:left;white-space:nowrap}th{position:sticky;top:0;background:#111b2d;color:#b8c4d8}tbody tr:hover{background:rgba(143,122,255,.06)}code{font-size:.68rem;color:#c8d2e4}.active{color:var(--success)}.error{color:var(--danger)}@media(max-width:700px){.filters{grid-template-columns:1fr}}</style>