<script lang="ts">
import {chatCompletionStream,getModels} from "../lib/api";
import type {ChatMessage,Model} from "../lib/api";
type Mode="single"|"selected"|"providers";type State="waiting"|"running"|"done"|"error";
type Result={id:string;modelId:string;modelName:string;provider:string,state:State,text:string,error?:string,ms?:number};
type Batch={id:string,prompt:string,created:string,results:Result[]};
let models=$state<Model[]>([]),mode=$state<Mode>("single"),single=$state(""),selected=$state<string[]>([]),prompt=$state(""),batches=$state<Batch[]>([]),running=$state(false),pageError=$state("");
const active=$derived(models.filter(m=>m.enabled));const aborters=new Map<string,AbortController>();
$effect(()=>{void load()});
async function load(){try{models=await getModels();if(!models.some(m=>m.id===single))single=models[0]?.id??"";selected=selected.filter(id=>models.some(m=>m.id===id));if(!selected.length&&models[0])selected=[models[0].id];pageError=""}catch(e){pageError=e instanceof Error?e.message:String(e)}}
function toggle(id:string){selected=selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]}
function targets(){if(mode==="single")return active.filter(m=>m.id===single);if(mode==="selected")return active.filter(m=>selected.includes(m.id));const map=new Map<string,Model>();for(const m of active)if(!map.has(m.provider))map.set(m.provider,m);return [...map.values()]}
function patch(batchId:string,resultId:string,change:Partial<Result>){batches=batches.map(b=>b.id!==batchId?b:{...b,results:b.results.map(r=>r.id===resultId?{...r,...change}:r)})}
function append(batchId:string,resultId:string,chunk:string){batches=batches.map(b=>b.id!==batchId?b:{...b,results:b.results.map(r=>r.id===resultId?{...r,text:r.text+chunk}:r)})}
function execute(batchId:string,result:Result,text:string){return new Promise<void>(resolve=>{const started=performance.now();patch(batchId,result.id,{state:"running"});const controller=chatCompletionStream(result.modelId,[{role:"user",content:text}] as ChatMessage[],chunk=>append(batchId,result.id,chunk),()=>{patch(batchId,result.id,{state:"done",ms:Math.round(performance.now()-started)});aborters.delete(result.id);resolve()},error=>{patch(batchId,result.id,{state:"error",error:error.message,ms:Math.round(performance.now()-started)});aborters.delete(result.id);resolve()});aborters.set(result.id,controller)})}
async function start(){const text=prompt.trim(),list=targets();if(!text||!list.length||running)return;const id=crypto.randomUUID(),results=list.map(m=>({id:crypto.randomUUID(),modelId:m.id,modelName:m.name,provider:m.provider,state:"waiting" as State,text:""}));batches=[{id,prompt:text,created:new Date().toISOString(),results},...batches];prompt="";running=true;await Promise.allSettled(results.map(r=>execute(id,r,text)));running=false}
function stop(){for(const c of aborters.values())c.abort();aborters.clear();running=false}
function clear(){stop();batches=[];pageError=""}
function key(e:KeyboardEvent){if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void start()}}
</script>
<div class="pg"><header><div class="modes"><button class:on={mode==="single"} onclick={()=>mode="single"}>Ein Modell</button><button class:on={mode==="selected"} onclick={()=>mode="selected"}>Auswahl</button><button class:on={mode==="providers"} onclick={()=>mode="providers"}>Je Provider 1×</button></div><div><span>{new Set(active.map(m=>m.provider)).size} Provider · {active.length} Modelle</span><button onclick={load}>Aktualisieren</button><button onclick={clear}>Leeren</button></div></header><section class="pick">{#if mode==="single"}<select bind:value={single}>{#each active as m}<option value={m.id}>{m.name} · {m.provider}</option>{/each}</select>{:else if mode==="selected"}<div class="checks">{#each active as m}<label class:on={selected.includes(m.id)}><input type="checkbox" checked={selected.includes(m.id)} onchange={()=>toggle(m.id)}/><span><b>{m.name}</b><small>{m.provider}</small></span></label>{/each}</div>{:else}<div class="chips">{#each targets() as m}<span><b>{m.provider}</b>{m.name}</span>{/each}</div>{/if}</section><section class="compose"><textarea bind:value={prompt} onkeydown={key} rows="3" placeholder="Dieselbe Aufgabe an alle ausgewählten Modelle senden …"></textarea>{#if running}<button class="stop" onclick={stop}>Stoppen</button>{:else}<button class="run" onclick={start} disabled={!prompt.trim()||!targets().length}>{targets().length} testen</button>{/if}</section>{#if pageError}<p class="error">{pageError}</p>{/if}<main>{#if !batches.length}<div class="empty"><b>Modelle vergleichen</b><span>Ein Modell, freie Auswahl oder automatisch ein Modell je Provider.</span></div>{/if}{#each batches as batch (batch.id)}<section class="batch"><div class="batchhead"><b>{batch.prompt}</b><time>{new Date(batch.created).toLocaleTimeString("de-DE")}</time></div><div class="results">{#each batch.results as r (r.id)}<article><header><div><b>{r.modelName}</b><small>{r.provider} · {r.modelId}</small></div><i>{r.state}</i></header><pre class:error={r.state==="error"}>{r.text||r.error||(r.state==="waiting"?"Wartet …":"Antwort wird erzeugt …")}</pre>{#if r.ms!==undefined}<footer>{(r.ms/1000).toFixed(1)} s</footer>{/if}</article>{/each}</div></section>{/each}</main></div>
<style>.pg{min-height:calc(100vh - 7rem);padding:1rem}.pg>header,.pick,.compose{border:1px solid var(--border);background:var(--card-bg)}.pg>header{display:flex;justify-content:space-between;gap:.6rem;padding:.7rem;border-radius:12px 12px 0 0}.pg>header>div,.modes{display:flex;align-items:center;gap:.4rem;flex-wrap:wrap}button{min-height:36px;padding:0 .7rem;border:1px solid var(--border);border-radius:8px;background:rgba(255,255,255,.04);color:var(--text)}button.on,.run{background:var(--accent)}button:disabled{opacity:.4}.pg>header span{color:var(--muted);font-size:.7rem}.pick{padding:.7rem;border-top:0}.pick select,.compose textarea{width:100%;padding:.65rem;border:1px solid var(--border);border-radius:8px;background:var(--surface);color:var(--text)}.checks{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:.4rem}.checks label{display:flex;gap:.4rem;padding:.5rem;border:1px solid var(--border);border-radius:8px}.checks label.on{border-color:var(--accent)}.checks b,.checks small{display:block}.checks small{color:var(--muted)}.chips{display:flex;flex-wrap:wrap;gap:.4rem}.chips span{display:grid;padding:.45rem;border:1px solid var(--border);border-radius:8px;color:var(--muted);font-size:.7rem}.chips b{color:var(--text)}.compose{display:flex;gap:.6rem;padding:.7rem;border-top:0;border-radius:0 0 12px 12px}.compose textarea{resize:vertical}.compose button{min-width:110px}.stop,.error{color:#ff9aaa}main{display:grid;gap:.8rem;margin-top:.8rem}.empty{display:grid;place-items:center;gap:.3rem;min-height:200px;color:var(--muted)}.batch{border:1px solid var(--border);border-radius:12px;overflow:hidden}.batchhead{display:flex;justify-content:space-between;padding:.7rem;border-bottom:1px solid var(--border)}.batchhead time{color:var(--muted);font-size:.7rem}.results{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:.6rem;padding:.6rem}.results article{border:1px solid var(--border);border-radius:9px;background:var(--card-bg);overflow:hidden}.results article header{display:flex;justify-content:space-between;padding:.6rem;border-bottom:1px solid var(--border)}.results small{display:block;color:var(--muted)}.results i{font-style:normal;color:var(--muted)}pre{min-height:120px;max-height:450px;overflow:auto;margin:0;padding:.7rem;white-space:pre-wrap;font:inherit}.results footer{padding:.35rem;text-align:right;color:var(--muted);font-size:.65rem}@media(max-width:720px){.pg>header,.compose{flex-direction:column}.results{grid-template-columns:1fr}}</style>