<script lang="ts">
import {onMount} from "svelte";
import {PROVIDERS} from "../lib/providers";
type Job={id:string;providerId:string;status:string;message?:string;accountLabel?:string;failureReason?:string};
type Runtime={id:string;status:string;runnable:boolean;accounts:number;validAccounts:number;models:number;lastError?:string|null};
let jobs=$state<Job[]>([]),runtime=$state<Runtime[]>([]),query=$state(""),region=$state("all"),busy=$state(""),error=$state("");
const rows=$derived(PROVIDERS.filter(p=>{const q=query.toLowerCase();return(!q||[p.id,p.label,...p.aliases].some(v=>v.toLowerCase().includes(q)))&&(region==="all"||p.region===region)}));
onMount(()=>{void refresh();const timer=setInterval(refresh,3000);return()=>clearInterval(timer)});
async function refresh(){try{const [jobsRes,runtimeRes]=await Promise.all([fetch("/api/discovery/logins",{cache:"no-store"}),fetch("/api/provider-runtime",{cache:"no-store"})]);if(!jobsRes.ok||!runtimeRes.ok)throw new Error(`HTTP ${jobsRes.status}/${runtimeRes.status}`);jobs=(await jobsRes.json()).jobs;runtime=await runtimeRes.json();error=""}catch(e){error=e instanceof Error?e.message:String(e)}}
const jobFor=(id:string)=>jobs.find(j=>j.providerId===id);const runFor=(id:string)=>runtime.find(r=>r.id===id);
async function login(id:string){busy=id;try{const response=await fetch("/api/discovery/logins",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({providerId:id})});const body=await response.json();if(!response.ok)throw new Error(body.error??`HTTP ${response.status}`);await refresh()}catch(e){error=e instanceof Error?e.message:String(e)}finally{busy=""}}
</script>
<div class="page"><header><div><small>PROVIDER REGISTER</small><h2>Provider</h2><p>{rows.length} Anbieter · getrennte Browserprofile</p></div><button onclick={refresh}>Aktualisieren</button></header><section class="filters"><input bind:value={query} placeholder="Provider suchen …"/><select bind:value={region}><option value="all">Alle Regionen</option><option value="global">Global</option><option value="china">China</option></select></section>{#if error}<p class="error">{error}</p>{/if}<div class="grid"><table><thead><tr><th>#</th><th>Provider</th><th>ID</th><th>Region</th><th>Auth</th><th>Profil</th><th>Accounts</th><th>Modelle</th><th>Runtime</th><th>Letzter Login</th><th>Aktion</th></tr></thead><tbody>{#each rows as p,i (p.id)}{@const job=jobFor(p.id)}{@const run=runFor(p.id)}<tr><td>{i+1}</td><td><span class="dot" style={`--dot:${p.color}`}></span><b>{p.label}</b></td><td><code>{p.id}</code></td><td>{p.region}</td><td>{p.authType}</td><td>{p.authType==="web-login"?p.aliases[0]:"–"}</td><td>{run?`${run.validAccounts}/${run.accounts}`:"0/0"}</td><td>{run?.models??0}</td><td><span class="runtime {run?.status??"unknown"}">{run?.status??"unknown"}</span></td><td>{job?.message??job?.status??"–"}{#if job?.accountLabel}<small>{job.accountLabel}</small>{/if}</td><td>{#if p.authType==="web-login"}<button onclick={()=>login(p.id)} disabled={busy===p.id||["starting","waiting-for-user","saving"].includes(job?.status??"")}>{busy===p.id?"…":job?.status==="succeeded"?"Neu anmelden":"Login"}</button>{:else}<span>API-Key</span>{/if}</td></tr>{/each}</tbody></table></div></div>
<style>.page{padding:.25rem 0 2rem}header{display:flex;justify-content:space-between;align-items:end;margin-bottom:.6rem}header small{color:var(--accent-secondary)}h2{margin:.2rem 0}header p{margin:0;color:var(--muted)}button,input,select{min-height:34px;border:1px solid var(--border);border-radius:5px;background:var(--surface);color:var(--text);padding:0 .55rem}.filters{display:grid;grid-template-columns:1fr 170px;gap:.4rem;padding:.5rem;border:1px solid var(--border);border-bottom:0;background:var(--card-bg)}.grid{overflow:auto;border:1px solid var(--border)}table{width:100%;min-width:1250px;border-collapse:collapse;font-size:.72rem}th,td{padding:.5rem .6rem;border-right:1px solid rgba(151,166,196,.12);border-bottom:1px solid rgba(151,166,196,.12);text-align:left;white-space:nowrap}th{position:sticky;top:0;background:#111b2d;color:#b8c4d8}tbody tr:hover{background:rgba(143,122,255,.06)}.dot{display:inline-block;width:8px;height:8px;margin-right:.4rem;border-radius:50%;background:var(--dot)}td small{display:block;color:var(--muted)}code{font-size:.66rem}.runtime{padding:.15rem .4rem;border-radius:999px;background:rgba(145,160,184,.12)}.runtime.healthy{color:var(--success)}.runtime.degraded,.runtime.login-required{color:#ffd166}.runtime.not-implemented{color:var(--danger)}.error{color:var(--danger)}@media(max-width:700px){.filters{grid-template-columns:1fr}}</style>