import { access, writeFile } from "node:fs/promises";
import { constants } from "node:fs";
import { homedir } from "node:os";
import { join, resolve } from "node:path";
import { DEFAULT_GATEWAY_URL } from "../app-meta.js";

export const GENERIC_AGENT_SOURCE_URL = "https://github.com/lsdefine/genericagent";

export interface GenericAgentConfigOptions {
  sourceDir?: string;
  gatewayUrl?: string;
  model?: string;
}

export function resolveGenericAgentSourceDir(value?: string): string {
  const fallback = join(homedir(), ".local", "share", "nova", "agents", "genericagent");
  return resolve(value?.trim() || process.env.NOVA_GENERIC_AGENT_HOME || fallback);
}

export function normalizeGenericGatewayUrl(value?: string): string {
  return (value?.trim() || process.env.NOVA_GATEWAY_URL || DEFAULT_GATEWAY_URL).replace(/\/+$/, "");
}

export async function genericAgentPathExists(path: string): Promise<boolean> {
  try {
    await access(path, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

export async function configureGenericAgent(
  options: GenericAgentConfigOptions = {},
): Promise<string> {
  const sourceDir = resolveGenericAgentSourceDir(options.sourceDir);
  const configPath = join(sourceDir, "mykey.py");
  const gatewayUrl = normalizeGenericGatewayUrl(options.gatewayUrl);
  const model = options.model?.trim() || process.env.NOVA_MODEL || "gpt-4o";

  if (!(await genericAgentPathExists(join(sourceDir, "agentmain.py")))) {
    throw new Error(
      `GenericAgent wurde unter ${sourceDir} nicht gefunden. Setze NOVA_GENERIC_AGENT_HOME auf den Repository-Pfad.`,
    );
  }

  await writeFile(
    configPath,
    [
      "# Generated by Nova. Provider credentials remain inside Nova.",
      "native_oai_config = {",
      "    'name': 'nova',",
      "    'apikey': 'nova-local',",
      `    'apibase': ${JSON.stringify(gatewayUrl)},`,
      `    'model': ${JSON.stringify(model)},`,
      "    'api_mode': 'chat_completions',",
      "}",
      "",
    ].join("\n"),
    { encoding: "utf8", mode: 0o600 },
  );

  return configPath;
}
