import { access, mkdir, writeFile } from "node:fs/promises";
import { constants } from "node:fs";
import { dirname, join } from "node:path";
import { APP_NAME, YOYO_SOURCE_URL } from "../app-meta.js";
import { normalizeGatewayUrl } from "./yoyo-adapter.js";

export interface InitNovaAgentOptions {
  directory?: string;
  gatewayUrl?: string;
  model?: string;
}

export interface InitNovaAgentResult {
  created: string[];
  skipped: string[];
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

export async function initNovaAgentProject(
  options: InitNovaAgentOptions = {},
): Promise<InitNovaAgentResult> {
  const directory = options.directory ?? process.cwd();
  const created: string[] = [];
  const skipped: string[] = [];
  const configPath = join(directory, ".yoyo.toml");
  const instructionsPath = join(directory, ".yoyo", "instructions.md");
  const model = options.model?.trim() || process.env.NOVA_MODEL || "gpt-4o";
  const gatewayUrl = normalizeGatewayUrl(options.gatewayUrl);

  if (await fileExists(configPath)) {
    skipped.push(configPath);
  } else {
    await writeFile(
      configPath,
      [
        "# Generated by Nova for the yoyo-evolve agent backend.",
        'provider = "custom"',
        `model = ${JSON.stringify(model)}`,
        `base_url = ${JSON.stringify(gatewayUrl)}`,
        'thinking = "medium"',
        "max_turns = 50",
        "",
      ].join("\n"),
      { encoding: "utf8", mode: 0o600 },
    );
    created.push(configPath);
  }

  if (await fileExists(instructionsPath)) {
    skipped.push(instructionsPath);
  } else {
    await mkdir(dirname(instructionsPath), { recursive: true, mode: 0o700 });
    await writeFile(
      instructionsPath,
      [
        `# ${APP_NAME} Agent Context`,
        "",
        "Use Nova's local OpenAI-compatible gateway for model access.",
        "Never print cookies, tokens, passwords, or account file contents.",
        "Run the project's quality gates before committing changes.",
        "Prefer reversible edits and keep changes focused.",
        "",
        `Agent backend: ${YOYO_SOURCE_URL}`,
        "",
      ].join("\n"),
      { encoding: "utf8", mode: 0o600 },
    );
    created.push(instructionsPath);
  }

  return { created, skipped };
}
